[package]
name = "yolo_ide"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.12.1", features = ["debug", "tokio", "highlighter"] }
tokio = { version = "1.37.0", features = ["fs"] }
rfd = "0.14.1"